spring:
  cloud:
    config:
      server:
        # native:
          # # Fore linux
          # searchLocations : file:/mnt/c/Projects/JAVA/melon_clone_project/config-repo
          # # For Window
          #  searchLocations : file:///c:/Projects/JAVA/melon_clone_project/config-repo
        git:
          uri: https://github.com/MelonClone/melon_config_repo
server:
  port: 8888

# spring:
#   cloud:
#     config:
#       server: file://Users/anilallewar/Documents/Anil Allewar/Trainings/Code Samples/Enterprise Java/Micro Services/sample-config