spring:
  cloud:
    config:
      server:
        native:
          # Fore linux
          searchLocations : file:/mnt/c/Projects/JAVA/melon_clone_project/config-repo
        #   # For Window
        #    searchLocations : file:///mnt/c/Projects/JAVA/melon_clone_project/config-repo
        # git:
        #   uri: file://mnt/c/Projects/JAVA/melon_clone_project/config-repo
server:
  port: 8888

# spring:
#   cloud:
#     config:
#       server: file://Users/anilallewar/Documents/Anil Allewar/Trainings/Code Samples/Enterprise Java/Micro Services/sample-config